/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavigationDrawer: typeof import('./components/AppNavigationDrawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoTextField: typeof import('./components/invoices/InfoTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDetails: typeof import('./components/invoices/TableDetails.vue')['default']
    TablePaymentMethods: typeof import('./components/invoices/TablePaymentMethods.vue')['default']
  }
}
