/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavigationDrawer: typeof import('./components/AppNavigationDrawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoTextField: typeof import('./components/invoices/InfoTextField.vue')['default']
    InvoiceClient: typeof import('./components/invoices/InvoiceClient.vue')['default']
    InvoiceFooter: typeof import('./components/invoices/InvoiceFooter.vue')['default']
    InvoiceMainTaxInfo: typeof import('./components/invoices/InvoiceMainTaxInfo.vue')['default']
    InvoiceOrganization: typeof import('./components/invoices/InvoiceOrganization.vue')['default']
    InvoiceTotals: typeof import('./components/invoices/InvoiceTotals.vue')['default']
    PaymentMethods: typeof import('./components/invoices/PaymentMethods.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableDetail: typeof import('./components/product/TableDetail.vue')['default']
    TableDetailCustomer: typeof import('./components/customers/TableDetailCustomer.vue')['default']
    TableDetailProduct: typeof import('./components/product/TableDetailProduct.vue')['default']
    TableDetails: typeof import('./components/invoices/TableDetails.vue')['default']
    TableEstablishment: typeof import('./components/establishments/TableEstablishment.vue')['default']
    TablePaymentMethods: typeof import('./components/invoices/TablePaymentMethods.vue')['default']
  }
}
