/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/customers/': RouteRecordInfo<'/customers/', '/customers', Record<never, never>, Record<never, never>>,
    '/customers/[uuid]': RouteRecordInfo<'/customers/[uuid]', '/customers/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/establishments/': RouteRecordInfo<'/establishments/', '/establishments', Record<never, never>, Record<never, never>>,
    '/establishments/[uuid]': RouteRecordInfo<'/establishments/[uuid]', '/establishments/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/invoices/': RouteRecordInfo<'/invoices/', '/invoices', Record<never, never>, Record<never, never>>,
    '/invoices/[uuid]': RouteRecordInfo<'/invoices/[uuid]', '/invoices/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[uuid]': RouteRecordInfo<'/products/[uuid]', '/products/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
  }
}
